# Generated by Django 4.0.1 on 2022-02-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('done', 'done')], default='active', max_length=6),
        ),
    ]
